
spring:
    application:
        name: atsumarii
    datasource:
        url: jdbc:mysql://localhost:3307/atsumarii_db?createDatabaseIfNotExist=true
        username: root
        password: rootpass
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                '[format_sql]': true
        database: mysql
        database-platform: org.hibernate.dialect.MySQL8Dialect
        defer-datasource-initialization: true
    sql:
        init:
            mode: ${SPRING_SQL_INIT_MODE:always}  # Control via environment variable
            data-locations: classpath:populate-safe.sql
            continue-on-error: true