
spring:
    application:
        name: atsumarii
    datasource:
        url: jdbc:mysql://localhost:3307/atsumarii_db?createDatabaseIfNotExist=true
        username: root
        password: test
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                '[format_sql]': true
        database: mysql
        database-platform: org.hibernate.dialect.MySQL8Dialect
        defer-datasource-initialization: true
    # sql:
    #     init:
    #         mode: always
    #         data-locations: classpath:populate.sql
    #         continue-on-error: false